language: rust

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar -jxf -
  - curl -L https://github.com/Kogia-sima/rust-covfix/releases/download/v0.2.1/rust-covfix-linux-x86_64.tar.xz | tar -Jxf - rust-covfix-linux-x86_64/rust-covfix --strip-components=1

matrix:
  include:
    - os: linux
      rust: nightly

script:
  - ./ccov.sh ci
