[book]
title = "rew"
description = "The Swiss Army Knife of line-oriented text processing. Transform text by composing parallel shell pipelines!"
authors = ["Jan Pikl"]
language = "en"
src = "docs"

[output.html]
git-repository-url = "https://github.com/jpikl/rew"
git-repository-icon = "fa-github"
additional-css = ["docs/custom.css"]
