[package]
name = "rew"
version = "0.1.0"
description = "Rewrite FS paths using a pattern."
authors = ["Jan Pikl <pikl.jan@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.14"
clap = "3.0.0-beta.1"
lazy_static = "1.4.0"
regex = "1"
termcolor = "1.1.0"
unidecode = "0.3.0"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
assert_cmd = "1.0.1"
indoc = "1.0"
predicates = "1.0.5"

[[bin]]
name = "rew"
path = "src/bin/rew/main.rs"

[[bin]]
name = "mvb"
path = "src/bin/mvb/main.rs"

[[bin]]
name = "cpb"
path = "src/bin/cpb/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

