[package]
name = "rew"
version = "0.1.0"
description = "Rewrite FS paths using a pattern."
authors = ["Jan Pikl <pikl.jan@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.14"
lazy_static = "1.4.0"
regex = "1"
structopt = "0.3.14"
termcolor = "1.1.0"
unidecode = "0.3.0"
uuid = { version = "0.8", features = ["v4"] }
