[package]
name = "rew"
version = "0.1.0"
description = "A CLI tool that rewrites FS paths according to a pattern."
keywords = ["tool", "command-line", "replace", "rename", "regex", "files"]
authors = ["Jan Pikl <pikl.jan@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.14"
clap = "3.0.0-beta.1"
fs_extra = "1.2.0"
indoc = "1.0"
lazy_static = "1.4.0"
normpath = "0.1"
regex = "1"
same-file = "1"
termcolor = "1.1.0"
unidecode = "0.3.0"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
assert_cmd = "1.0.1"
assert_fs = "1.0.0"
ntest = "0.7.2"
predicates = "1.0.5"

[[bin]]
name = "rew"
path = "src/bin/rew/main.rs"

[[bin]]
name = "mvb"
path = "src/bin/mvb/main.rs"

[[bin]]
name = "cpb"
path = "src/bin/cpb/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

