[package]
name = "rew"
version = "0.1.0"
description = "Rewrite FS paths using a pattern."
authors = ["Jan Pikl <pikl.jan@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.14"
lazy_static = "1.4.0"
regex = "1"
structopt = "0.3.14"
termcolor = "1.1.0"
unidecode = "0.3.0"
uuid = { version = "0.8", features = ["v4"] }

[[bin]]
name = "rew"
path = "src/bin/rew/main.rs"

[[bin]]
name = "bmv"
path = "src/bin/bmv/main.rs"

[[bin]]
name = "bcp"
path = "src/bin/bcp/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

