[package]
name = "rew-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rew = { path = ".." }

[[bin]]
name = "pattern"
path = "fuzz_targets/pattern.rs"
test = false
doc = false
bench = false
