name: Pages

on:
  workflow_dispatch:
  push:
    branches: [ stable-docs ]
    paths: [ 'docs/**', CHANGELOG.md , LICENSE.md, mkdocs.yml ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install mkdocs material
        run: pip install mkdocs-material

      - name: Deploy pages
        run: mkdocs gh-deploy --force
