name: Release

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os-name: linux
            target: x86_64-unknown-linux-gnu
            architecture: x86_64
            binary-postfix: ''
            use-cross: false

          - os: ubuntu-latest
            os-name: linux
            target: i686-unknown-linux-gnu
            architecture: i686
            binary-postfix: ''
            use-cross: true

          - os: ubuntu-latest
            os-name: linux
            target: aarch64-unknown-linux-gnu
            architecture: arm64
            binary-postfix: ''
            use-cross: true

          - os: windows-latest
            os-name: windows
            target: x86_64-pc-windows-msvc
            architecture: x86_64
            binary-postfix: '.exe'
            use-cross: false

          - os: macos-latest
            os-name: macos
            target: x86_64-apple-darwin
            architecture: x86_64
            binary-postfix: ''
            use-cross: false

    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install strip
        if: ${{ matrix.target == 'aarch64-unknown-linux-gnu' }}
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install -y binutils-aarch64-linux-gnu

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.use-cross }}
          toolchain: stable
          args: --release --target ${{ matrix.target }}

      - name: Package binary
        shell: bash
        run: |
          BINARY=rew${{ matrix.binary-postfix }}
          VERSION=${GITHUB_REF/refs\/tags\/v/}
          REALEASE=rew-$VERSION-${{ matrix.os-name }}-${{ matrix.architecture }}

          cd target/${{ matrix.target }}/release

          if [[ ${{ matrix.target }} == aarch64-unknown-linux-gnu ]]; then
            aarch64-linux-gnu-strip $BINARY
          else
            strip $BINARY
          fi

          tar czvf $REALEASE.tar.gz $BINARY

          if [[ ${{ runner.os }} == Windows ]]; then
            certutil -hashfile $REALEASE.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $REALEASE.sha256
          else
            shasum -a 256 $REALEASE.tar.gz > $REALEASE.sha256
          fi

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/rew-*.tar.gz
            target/${{ matrix.target }}/release/rew-*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --allow-dirty --token ${{ secrets.CARGO_API_KEY }}
